version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: bullseye

    ports:
      - 9000:9000

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    user: vscode

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev


volumes:
  db-data: null
