version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: bullseye

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    network_mode: service:db
    
    user: vscode

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev


volume:
  db-data:
